### ISSUE TITLE
parse_taxonomy_table issue

### ISSUE THREAD

**Issue by andrluis** [grunwaldlab/metacoder#138]
Hey guys:

I trust you are doing great! Thanks for the awesome package you created.

I'm testing metacodeR through the example of 'voting geography' (https://grunwaldlab.github.io/metacoder_documentation/publication--08--voting.html), and am getting errors when running the function parse_taxonomy_table.

Everything before the below command line was being fine.

Then, I got an error here:
##
> voting_data <- parse_taxonomy_table(input = data, taxon_col = c("class" = -1), other_col_type = "obs_info", class_sep = "\\|")
##
Error:
##
Error in parse_taxonomy_table(input = data, taxon_col = c(class = -1),  : 
  argument "file_path" is missing, with no default

> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X El Capitan 10.11.6

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] metacoder_0.1.2

loaded via a namespace (and not attached):
[1] magrittr_1.5   R6_2.2.0       assertthat_0.1 DBI_0.5-1      tools_3.3.2    dplyr_0.5.0   
[7] tibble_1.2     Rcpp_0.12.9   

Can you please help me to find why this is happening?

Thank you,

Andre

**Comment by zachary-foster** [comment]
Hi @andrluis, thanks for the report! That example was run using the development version of metacoder, but I forgot to put a notice on the page about that. It should work if you install the development version:

```
devtools::install_github(repo="grunwaldlab/metacoder@dev")
```

I will be merging the development version into a CRAN update soon, so it will work with the normal version soon too. 

The problem was that the CRAN verison of `parse_taxonomy_table` only accepts file paths and the new version accepts data.frames as well.

**Comment by zachary-foster** [comment]
@andrluis said this worked via Google Groups.
