### ISSUE TITLE
How to specify specific groups for a differential heat tree

### ISSUE THREAD

**Issue by ealam** [grunwaldlab/metacoder#216]
I'm still new to R and I was wondering how to amend the "groups = hmp_samples$body_site" code to specify specific groups (e.g. Nose and Stool) for comparison in differential heat tree.

**Comment by zachary-foster** [comment]
Hello @ealam! I assume you are following the readme example, so I will reply in that context. So you have two options: 

**1.** Subset the result of `compare_groups` to just the comparison you are interested:

```r
obj <- filter_obs(obj, "diff_table", treatment_1 == "Nose", treatment_2 == "Stool")
```

This is the same as 

```r
obj <- obj$data$diff_table[obj$data$diff_table$treatment_1 == "Nose" & obj$data$diff_table$treatment_2 == "Stool", ]
```

**2.** Only compare the two groups in the first place:

```r
compare_groups(obj, dataset = "tax_abund",
               cols = hmp_samples$sample_id,
               groups = hmp_samples$body_site, 
               combinations = list(c("Nose", "Stool")))
```

Since there are only two now, you can use the code like that in the "Comparing two treatments/groups"  section of the readme to make a differential heat tree.

**Comment by ealam** [comment]
Thank you, this works great!

**Comment by zachary-foster** [comment]
Nice, I am going to close this, but you can reopen if new questions arise
