### ISSUE TITLE
 calculating taxon_abundance

### ISSUE THREAD

**Issue by P-alonso** [grunwaldlab/metacoder#269]
Hello @zachary-foster

I attended your Phytobiome Conference in Montpellier last year. I manage now to analyze my data with Metacoder package. I am working on the rice microbiome, I'm looking the microbial communities of tow rice genotypes and I want to realize a difference between the microbial communities of the tow genotypes.

Firstly, I rarefyed my data set using the following code: `obj$data$otu_rarefied <- rarefy_obs (obj, "otu_counts", other_cols = TRUE)`. it works but the rarefy_obs function has modified my OTU_ID column (it is a numeric column). How can I specify to exclude this column?
The I do not understand, why when I'm calculating the taxon abundance with the following code `obj$data$tax_abund <- calc_taxon_abund (obj, "otu_rarefied")` I'm increasing the number of lines.
Should not have less lines if I sum the OTU with the same taxon?

**Comment by zachary-foster** [comment]
Hello @P-alonso, welcome to GitHub!

> How can I specify to exclude this column?

You can specify which columns to use with the `cols` option. See `?rarefy_obs` for examples. You could also convert it to a character vector with `as.character` if you prefer. Either way, I think it makes sense for an ID to be a character vector so that it does not get confused with an index. For example:

``` r
x = letters[1:10]
names(x) <- rev(1:10)
x
#>  10   9   8   7   6   5   4   3   2   1 
#> "a" "b" "c" "d" "e" "f" "g" "h" "i" "j"

y = 1:3

x[y]
#>  10   9   8 
#> "a" "b" "c"
x[as.character(y)]
#>   1   2   3 
#> "j" "i" "h"
```

<sup>Created on 2019-07-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

> I'm increasing the number of lines. Should not have less lines if I sum the OTU with the same taxon?

You should get one line per taxon. If you have more taxa than OTUs, then that would be expected. Each OTUs belongs to multiple taxa. For example, an OTU with this classification:

`Eukaryota;Heterokontophyta;Stramenopiles;Oomycetes;Peronosporales;Peronosporaceae;Phytophthora`

Belongs to 7 taxa. If that was the only OTU in my data set, then `calc_taxon_abund` would return 7 lines.

**Comment by P-alonso** [comment]
Thanks for the quick reply and your help!

I transformed my OTU ID to a character vector and it work now, the rarefaction is done only on the abundance data. 

Then, I understand better now why I had more line in tax_abund tibble than OTU_count tibble. But I still have a question how can I keep the taxonomic assignation for the extra lines? Currently I had only the taxon-id in this table?

Thank again for your help

**Comment by zachary-foster** [comment]
You are welcome! I am glad it worked out.

> how can I keep the taxonomic assignation for the extra lines? Currently I had only the taxon-id in this table?

I am not sure what you mean by 'taxonomic assignation'. Do you mean there are columns in the OTU table that you want in the taxon abundance table?

**Comment by P-alonso** [comment]
Hi, 
As I have more rows in Tax_abund tibble than in OTU table, is it possible to include in the tax_abund tibble a column with the taxonomic assignation of each taxon?

**Comment by zachary-foster** [comment]
Do you mean something like this? 

```r
obj$data$tax_abund$tax <- classifications(obj)[obj$data$tax_abund$taxon_id]
```

**Comment by P-alonso** [comment]
Thank you so much for your help! This is exactly what I wanted

**Comment by zachary-foster** [comment]
No problem!
