### ISSUE TITLE
See if any dependencies can be dropped

### ISSUE THREAD

**Issue by zachary-foster** [grunwaldlab/metacoder#29]
There are a lot of dependencies that are only use rarely and possibly could be removed.

**Comment by zkamvar** [comment]
It's worth mentioning here:

Dependency hell is very real. That being said, if you have continuous integration, and depend on R packages that have good maintainers (like the RopenSci people or hadley) you shall not fear them.

You may end up actually including more imports because as of R version 3.2, you should explicitly state which non-base packages you use, which includes things like stats and utils. I'm pretty sure R CMD Check will throw a NOTE about those and then potentially give you a command to add them to your imports (not assuming Roxygen).
