### ISSUE TITLE
Does removing low-abundance counts completely remove them from pairwise comparisons?

### ISSUE THREAD

**Issue by catherineel** [grunwaldlab/metacoder#319]
Sorry I'm very new to R and microbiome sequencing, so please excuse me if this is a dumb question.

When you remove low-abundance counts and make them 0, does that remove the sample/group from pairwise comparison?

For example, I am trying to see if there are any significant changes between the control and treatment groups. 

I suspect that the treatment group may "kill off" certain species, making all the counts extremely low and therefore 0 using your script _(obj$data$tax_data <- zero_low_counts(obj, dataset = "tax_data", min_count = 5))_ - which would be a significant finding for me OR the reverse, where a species is generally very low (close to 0) in control, but the treatment increases the population of this species.

When I create the heat tree, will this be taken into account and shown in the tree when I perform a pairwise comparison, or does it only work with samples that have valid numbers to compare?

**Comment by zachary-foster** [comment]
Zeroing low counts does not remove the taxon/OTU/ASV from consideration, it just makes it the same as if that taxon/OTU/ASV had no reads in that sample in the first place. The taxon would still be plotted, unless you filtered those taxa out somehow before plotting. The only time it would remove a taxon/OTU/ASV is if you had code to remove any taxon/OTU/ASV that has 0 in all samples. In that case, it would be possible that zeroing low counts could make that taxon/OTU/ASV zero in all samples. Does that make sense?

**Comment by catherineel** [comment]
Oh okay that makes sense, thank you.

So if I used the next script, would this remove taxon/OTU/ASV that has 0 in some samples OR only if all samples are 0, and therefore not display them in the heat tree?

_obj <- filter_obs(obj, "otu_counts", ! no_reads, drop_taxa = TRUE)_

**Comment by zachary-foster** [comment]
The `no_reads` there was generated with this code:

```r
no_reads <- rowSums(obj$data$tax_data[, hmp_samples$sample_id]) == 0
```

Which checks of the sum of read counts for each OTU in all samples is 0, so any OTU that has no reads in all the samples is removed. If the removed OTUs were the only ones representing a taxon, then yes, that taxon would not be displayed. Heat trees show per-taxon data, not per-OTU data, but the per-taxon counts are generated from the per-OTU counts, so they are related.  by the way, you dont have to do that filtering step if you dont want to. You can display taxa with a count of 0, it just might be confusing. I am filtering out low counts in the example since that is typical of microbiome analyses.

**Comment by catherineel** [comment]
Yeah you're right the data is a bit messier and confusing after keeping the taxa with a count of 0, so I'll stick to filtering it out. Thanks for the clarification!

**Comment by zachary-foster** [comment]
No problem!
